const actions = {
    GET_TODO_LIST: 'GET_TODO_LIST',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    UPDATE_STATUS: 'UPDATE_STATUS',
    UPDATE_URGENCY: 'UPDATE_URGENCY',
    DELETE_SELECTED: 'DELETE_SELECTED',
    CLEAR_TODO_LIST: 'CLEAR_TODO_LIST'

};

export default actions;